# Homework Starter — Stage 6: Data Preprocessing
Use this notebook to apply your cleaning functions and save processed data.

In [1]:
import pandas as pd
import numpy as np
from src.cleaning import fill_missing_median
from src.cleaning import drop_missing
from src.cleaning import normalize_data
from src.cleaning import correct_column_types

In [2]:
# Generate demo CSV if not exists
import os
import pandas as pd

csv_path = 'data/raw/sample_data.csv'
os.makedirs('data', exist_ok=True)

if not os.path.exists(csv_path):
    df_demo = pd.DataFrame({
        'numeric_col': [10, None, 40, 55, 70],
        'category_col': ['A', 'B', 'A', 'B', 'C'],
        'price': ['$100', '$200', '$150', None, '$250'],
        'date_str': ['2025-08-01','2025-08-02',None,'2025-08-04','2025-08-05'],
        'category': ['Electronics','Furniture','Toys','Clothing',None]
    })
    df_demo.to_csv(csv_path, index=False)
    print(f"Demo CSV created at {csv_path}")
else:
    print(f"CSV already exists at {csv_path}")

CSV already exists at data/raw/sample_data.csv

## Load Raw Dataset

In [3]:
df = pd.read_csv('data/raw/sample_data.csv')
df.head()

   numeric_col category_col price    date_str     category
0         10.0            A  $100  2025-08-01  Electronics
1          NaN            B  $200  2025-08-02    Furniture
2         40.0            A  $150         NaN         Toys
3         55.0            B   NaN  2025-08-04     Clothing
4         70.0            C  $250  2025-08-05          NaN

## Apply Cleaning Functions

In [4]:
# Apply reusable functions
df_cleaned = df.copy()
df_cleaned = fill_missing_median(df_cleaned)
df_cleaned = drop_missing(df_cleaned, threshold=0.5)
df_cleaned = normalize_data(df_cleaned)
df_cleaned = correct_column_types(df_cleaned)

# Inspect
df_cleaned.info()
df_cleaned.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   numeric_col   5 non-null      float64
 1   category_col  5 non-null      object
 2   price         4 non-null      float64
 3   date_str      4 non-null      object
 4   category      4 non-null      category
 5   date          4 non-null      datetime64[ns]
dtypes: category(1), datetime64[ns](1), float64(2), object(2)
memory usage: 537.0+ bytes

   numeric_col category_col  price    date_str     category       date
0        0.000            A  100.0  2025-08-01  electronics 2025-08-01
1        0.625            B  200.0  2025-08-02    furniture 2025-08-02
2        0.500            A  150.0         NaN         toys        NaT
3        0.750            B    NaN  2025-08-04     clothing 2025-08-04
4        1.000            C  250.0  2025-08-05          NaN 2025-08-05

## Save Cleaned Dataset

In [5]:
# Save
df_cleaned.to_csv('data/processed/combined_cleaned_data.csv', index=False)